version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.7

    working_directory: /go/src/github.com/minami14/idgo
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/goimports && diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./lib/*")) <(printf "")
      - run: go get -u golang.org/x/lint/golint && golint -set_exit_status ./...
      - run: go get -v -t -d ./...
      - run: go test -v ./...